name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/menil/jobgitops:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Validation Checks
        run: just validate
